import { CatalogItem } from "../types/catalog-data-types";

/**
 * Satellite Platform Registry (Simulation: Prefetched via GET /bus)
 */
export const mockBusData: CatalogItem[] = [
  {
    id: "bus-lm400",
    owner_org: "System",
    created_date: "2022-01-25T12:00:00Z",
    updated_date: "2022-01-25T12:00:00Z",
    created_by: "System",
    updated_by: "System",
    assembly_type: "bus",
    antaris_component_type: "Bus",
    name: "LM400",
    vendor: "Lockheed Martin",
    version: "H",
    category: "Bus",
    sub_category: "SmallSat Bus",
    is_global: true,
    is_visible: true,
    common_attributes: {
      id: "bus-lm400",
      count: 1,
      redundancy: 1,
      model: "LM400",
      vendor: "Lockheed Martin",
      title: "Lockheed Martin SmallSat Bus",
      description: "Next-generation adaptable SmallSat bus platform for LEO and MEO missions.",
      mass: { attribute_value: 750, attribute_unit: "kg" },
      dimensions: { length: 0.25, width: 0.25, height: 0.25, unit: "meters" },
      operating_temperature: { minimum_operating_temp: -40, maximum_operating_temp: 85, operating_temp_unit: "Celsius" },
    },
    bus_specific_attributes: {
      operating_system: "Antaris SatOS",
      mission_life: { attribute_value: 5, attribute_unit: "years" },
      mission_capabilities: ["Earth Observation", "Communications", "Orbital"],
      structure_type: "CubeSat",
      orbit_compatibility: ["LEO", "MEO"],
      launch_compatibility: ["PSLV"],
      dimensions: { length: 0.25, width: 0.25, height: 0.25, unit: "meters" },
      mass: { attribute_min: 500, attribute_max: 1000, attribute_unit: "grams" },
      payload_mass_supported: { attribute_min: 500, attribute_max: 1000, attribute_unit: "grams" },
      bus_voltage: { attribute_min: 12, attribute_max: 24, attribute_unit: "V" },
      bus_power_output: { attribute_min: 100, attribute_max: 200, attribute_unit: "Watts" },
      load_survival_capability: "static",
      pointing_accuracy: { attribute_value: 0.1, attribute_unit: "degrees" },
      radiation_tolerance: { attribute_min: 100, attribute_max: 120, attribute_unit: "kRad" },
      operating_temperature: { minimum_operating_temp: -40, maximum_operating_temp: 85, operating_temp_unit: "Celsius" },
      interfaces: [
        { interface_type: "data", interface_value: ["RS-422", "UART"] },
        { interface_type: "mount", interface_value: ["M3 fasteners", "4-bolt mounting interface"] }
      ],
      comm_data_rate: [
        { band_name: "S-Band", uplink_rate: 650, downlink_rate: 650, rate_unit: "Mbps" },
        { band_name: "X-Band", uplink_rate: 0, downlink_rate: 650, rate_unit: "Mbps" }
      ],
      payload_supported: ["EO Optical", "SAR", "IoT"],
      propulsion_type: "cold-gas"
    }
  }
];

/**
 * Hardware Component Registry (Simulation: Prefetched via GET /components)
 */
export const mockCatalogComponents: CatalogItem[] = [
  // --- PAYLOAD COMPONENTS ---
  {
    id: "payload-eo-1",
    owner_org: "System",
    created_date: "2023-01-01T00:00:00Z",
    updated_date: "2023-01-01T00:00:00Z",
    created_by: "System",
    updated_by: "System",
    assembly_type: "discrete",
    antaris_component_type: "Imaging_Payloads",
    name: "ARGUS-M",
    vendor: "Argon Systems",
    category: "Payload",
    sub_system: "earth-observation",
    sub_category: "Multispectral Imager",
    is_global: true,
    is_visible: true,
    common_attributes: {
      id: "payload-eo-1",
      count: 1,
      redundancy: 1,
      model: "ARGUS-M",
      vendor: "Argon Systems",
      title: "ARGUS-M Multispectral Imager",
      description: "Proven Earth observation imager with high-spectral resolution.",
      mass: { attribute_value: 12.5, attribute_unit: "kg" },
      dimensions: { length: 0.2, width: 0.2, height: 0.3, unit: "meters" },
      operating_temperature: { minimum_operating_temp: -20, maximum_operating_temp: 50, operating_temp_unit: "Celsius" },
    },
    component_specific_attributes: {
      gsd: "0.5m",
      swath: "15km",
      power: "12W"
    }
  },
  {
    id: "payload-comms-1",
    owner_org: "System",
    created_date: "2023-01-01T00:00:00Z",
    updated_date: "2023-01-01T00:00:00Z",
    created_by: "System",
    updated_by: "System",
    assembly_type: "discrete",
    antaris_component_type: "Radio_transceiver",
    name: "S-BAND X2",
    vendor: "SpaceLink",
    category: "Payload",
    sub_system: "comms",
    sub_category: "Transceiver",
    is_global: true,
    is_visible: true,
    common_attributes: {
      id: "payload-comms-1",
      count: 1,
      redundancy: 1,
      model: "S-BAND X2",
      vendor: "SpaceLink",
      title: "S-Band High-Rate Transceiver",
      description: "High-reliability S-band transceiver for mission data and TT&C.",
      mass: { attribute_value: 0.8, attribute_unit: "kg" },
      dimensions: { length: 0.1, width: 0.1, height: 0.05, unit: "meters" },
      operating_temperature: { minimum_operating_temp: -40, maximum_operating_temp: 80, operating_temp_unit: "Celsius" },
    },
    component_specific_attributes: {
      data_rate: "10 Mbps",
      power: "8W"
    }
  },
  {
    id: "payload-edge-1",
    owner_org: "System",
    created_date: "2023-01-01T00:00:00Z",
    updated_date: "2023-01-01T00:00:00Z",
    created_by: "System",
    updated_by: "System",
    assembly_type: "discrete",
    antaris_component_type: "Edge_node",
    name: "NEURAL-1",
    vendor: "Antaris",
    category: "Payload",
    sub_system: "edge",
    sub_category: "AI Accelerator",
    is_global: true,
    is_visible: true,
    common_attributes: {
      id: "payload-edge-1",
      count: 1,
      redundancy: 2,
      model: "NEURAL-1",
      vendor: "Antaris",
      title: "On-board AI Processing Node",
      description: "Edge computing node optimized for real-time satellite imagery analysis.",
      mass: { attribute_value: 1.2, attribute_unit: "kg" },
      dimensions: { length: 0.15, width: 0.15, height: 0.04, unit: "meters" },
      operating_temperature: { minimum_operating_temp: -30, maximum_operating_temp: 75, operating_temp_unit: "Celsius" },
    },
    component_specific_attributes: {
      tops: "24",
      power: "15W"
    }
  },

  // --- BUS COMPONENTS ---
  {
    id: "bus-cpu-1",
    owner_org: "System",
    created_date: "2023-01-01T00:00:00Z",
    updated_date: "2023-01-01T00:00:00Z",
    created_by: "System",
    updated_by: "System",
    assembly_type: "discrete",
    antaris_component_type: "Core_onboard_computer",
    name: "SAT-BRAIN X",
    vendor: "HexaCompute",
    category: "Bus",
    sub_system: "processor",
    sub_category: "Command & Data Handling",
    is_global: true,
    is_visible: true,
    common_attributes: {
      id: "bus-cpu-1",
      count: 1,
      redundancy: 2,
      model: "SBX-200",
      vendor: "HexaCompute",
      title: "High-Performance OBC",
      description: "Rad-hardened command and data handling system.",
      mass: { attribute_value: 0.5, attribute_unit: "kg" },
      dimensions: { length: 0.1, width: 0.1, height: 0.02, unit: "meters" },
      operating_temperature: { minimum_operating_temp: -40, maximum_operating_temp: 85, operating_temp_unit: "Celsius" },
    },
    component_specific_attributes: {
      ram: "16GB",
      power: "5W"
    }
  },
  {
    id: "bus-eps-1",
    owner_org: "System",
    created_date: "2023-01-01T00:00:00Z",
    updated_date: "2023-01-01T00:00:00Z",
    created_by: "System",
    updated_by: "System",
    assembly_type: "integrated",
    antaris_component_type: "EPS",
    name: "VOLT-CORE",
    vendor: "PowerSpace",
    category: "Bus",
    sub_system: "eps",
    sub_category: "Power Distribution",
    is_global: true,
    is_visible: true,
    common_attributes: {
      id: "bus-eps-1",
      count: 1,
      redundancy: 1,
      model: "VOLT-CORE 500",
      vendor: "PowerSpace",
      title: "Integrated Power System",
      description: "Complete power generation and distribution unit with battery management.",
      mass: { attribute_value: 3.2, attribute_unit: "kg" },
      dimensions: { length: 0.2, width: 0.2, height: 0.1, unit: "meters" },
      operating_temperature: { minimum_operating_temp: -10, maximum_operating_temp: 60, operating_temp_unit: "Celsius" },
    },
    component_specific_attributes: {
      efficiency: "94%",
      power: "10W"
    }
  },
  {
    id: "bus-adcs-1",
    owner_org: "System",
    created_date: "2023-01-01T00:00:00Z",
    updated_date: "2023-01-01T00:00:00Z",
    created_by: "System",
    updated_by: "System",
    assembly_type: "integrated",
    antaris_component_type: "iADCS",
    name: "HORIZON-3",
    vendor: "BlueOrbit",
    category: "Bus",
    sub_system: "adcs",
    sub_category: "Attitude Control",
    is_global: true,
    is_visible: true,
    common_attributes: {
      id: "bus-adcs-1",
      count: 1,
      redundancy: 1,
      model: "HORIZON-3",
      vendor: "BlueOrbit",
      title: "Integrated ADCS Module",
      description: "High-precision attitude determination and control suite.",
      mass: { attribute_value: 2.1, attribute_unit: "kg" },
      dimensions: { length: 0.1, width: 0.1, height: 0.1, unit: "meters" },
      operating_temperature: { minimum_operating_temp: -25, maximum_operating_temp: 70, operating_temp_unit: "Celsius" },
    },
    component_specific_attributes: {
      pointing_precision: "0.1deg",
      power: "6W"
    }
  },
  {
    id: "bus-gps-1",
    owner_org: "System",
    created_date: "2023-01-01T00:00:00Z",
    updated_date: "2023-01-01T00:00:00Z",
    created_by: "System",
    updated_by: "System",
    assembly_type: "discrete",
    antaris_component_type: "GPS",
    name: "NAV-STAR",
    vendor: "GlobalNav",
    category: "Bus",
    sub_system: "gps",
    sub_category: "GNSS Receiver",
    is_global: true,
    is_visible: true,
    common_attributes: {
      id: "bus-gps-1",
      count: 1,
      redundancy: 1,
      model: "NAV-STAR 10",
      vendor: "GlobalNav",
      title: "Precision GNSS Receiver",
      description: "High-accuracy position and timing receiver for LEO platforms.",
      mass: { attribute_value: 0.2, attribute_unit: "kg" },
      dimensions: { length: 0.05, width: 0.05, height: 0.01, unit: "meters" },
      operating_temperature: { minimum_operating_temp: -40, maximum_operating_temp: 85, operating_temp_unit: "Celsius" },
    },
    component_specific_attributes: {
      channels: "12",
      power: "2W"
    }
  },
  {
    id: "bus-temp-1",
    owner_org: "System",
    created_date: "2023-01-01T00:00:00Z",
    updated_date: "2023-01-01T00:00:00Z",
    created_by: "System",
    updated_by: "System",
    assembly_type: "discrete",
    antaris_component_type: "Temperature_sensor",
    name: "THERMO-SCAN",
    vendor: "ThermalLogic",
    category: "Bus",
    sub_system: "temperature",
    sub_category: "Sensors",
    is_global: true,
    is_visible: true,
    common_attributes: {
      id: "bus-temp-1",
      count: 4,
      redundancy: 1,
      model: "TS-100",
      vendor: "ThermalLogic",
      title: "Multipoint Thermal Sensor",
      description: "Distributed temperature monitoring for critical satellite components.",
      mass: { attribute_value: 0.05, attribute_unit: "kg" },
      dimensions: { length: 0.01, width: 0.01, height: 0.01, unit: "meters" },
      operating_temperature: { minimum_operating_temp: -100, maximum_operating_temp: 150, operating_temp_unit: "Celsius" },
    },
    component_specific_attributes: {
      accuracy: "+/- 0.5C",
      power: "0.1W"
    }
  },
  {
    id: "bus-thrust-1",
    owner_org: "System",
    created_date: "2023-01-01T00:00:00Z",
    updated_date: "2023-01-01T00:00:00Z",
    created_by: "System",
    updated_by: "System",
    assembly_type: "discrete",
    antaris_component_type: "Thruster",
    name: "PLASMA-FLUX",
    vendor: "IonicPropulsion",
    category: "Bus",
    sub_system: "thruster",
    sub_category: "Electric Propulsion",
    is_global: true,
    is_visible: true,
    common_attributes: {
      id: "bus-thrust-1",
      count: 1,
      redundancy: 1,
      model: "PF-HE-5",
      vendor: "IonicPropulsion",
      title: "Hall Effect Thruster",
      description: "High-efficiency electric propulsion for orbit maintenance.",
      mass: { attribute_value: 5.5, attribute_unit: "kg" },
      dimensions: { length: 0.3, width: 0.3, height: 0.2, unit: "meters" },
      operating_temperature: { minimum_operating_temp: -5, maximum_operating_temp: 100, operating_temp_unit: "Celsius" },
    },
    component_specific_attributes: {
      thrust: "5mN",
      power: "150W"
    }
  },
  {
    id: "custom-item-1",
    owner_org: "System",
    created_date: "2023-01-01T00:00:00Z",
    updated_date: "2023-01-01T00:00:00Z",
    created_by: "System",
    updated_by: "System",
    assembly_type: "discrete",
    antaris_component_type: "Other",
    name: "CUSTOM BOX",
    vendor: "User Defined",
    category: "Payload",
    sub_system: "custom",
    sub_category: "Misc",
    is_global: false,
    is_visible: true,
    common_attributes: {
      id: "custom-item-1",
      count: 1,
      redundancy: 1,
      model: "GENERIC-V1",
      vendor: "User Defined",
      title: "Custom User Payload Component",
      description: "Generic placeholder for user-specific specialized hardware.",
      mass: { attribute_value: 1.0, attribute_unit: "kg" },
      dimensions: { length: 0.1, width: 0.1, height: 0.1, unit: "meters" },
      operating_temperature: { minimum_operating_temp: -40, maximum_operating_temp: 85, operating_temp_unit: "Celsius" },
    },
    component_specific_attributes: {
      power: "0W"
    }
  }
];
