import type { CatalogItem } from "../types/catalog-data-types";

export const mockCatalogItems: CatalogItem[] = [
  {
    id: "1",
    name: "XDLINX 2M Imager",
    groupLabel: "Imager",
    category: "payload",
    subSystem: "earth-observation",
    specs: {
      size: "8 U",
      mass: "10 Kg",
      power: "6 W",
      gsd: "2 M",
      swath: "14 Km",
    },
    tags: ["USB", "LVDS"],
  },
  {
    id: "2",
    name: "SAR-X Band Radar",
    groupLabel: "SAR",
    category: "payload",
    subSystem: "earth-observation",
    specs: {
      size: "U24",
      mass: "42.0 kg",
      power: "150 W",
      gsd: "1.5 M",
      swath: "50 km",
    },
    tags: ["X-Band", "SAR"],
  },
  {
    id: "3",
    name: "HyperSpec-9",
    groupLabel: "Imager",
    category: "payload",
    subSystem: "earth-observation",
    specs: {
      size: "U6",
      mass: "7.2 kg",
      power: "15 W",
      gsd: "4 M",
      swath: "10 km",
    },
    tags: ["Hyperspectral"],
  },
  {
    id: "6",
    name: "AIS Receiver Pro",
    groupLabel: "AIS",
    category: "payload",
    subSystem: "comms",
    specs: {
      size: "1 U",
      mass: "0.5 Kg",
      power: "2 W",
      gsd: "12 M",
      swath: "N/A",
    },
    tags: ["AIS", "VHF"],
  },
  {
    id: "7",
    name: "L-Band SAR payload",
    groupLabel: "SAR",
    category: "payload",
    subSystem: "earth-observation",
    specs: {
      size: "U36",
      mass: "36.0 kg",
      power: "200 W",
      gsd: "1 M",
      swath: "60 km",
    },
    tags: ["L-Band", "SAR"],
  },
  {
    id: "8",
    name: "Antaris EPS Module",
    groupLabel: "Power",
    category: "bus",
    subSystem: "eps",
    specs: {
      size: "1 U",
      mass: "1.2 kg",
      power: "100 W",
    },
    tags: ["Li-Ion", "Standard"],
  },
  {
    id: "9",
    name: "Reaction Wheel V4",
    groupLabel: "ADCS",
    category: "bus",
    subSystem: "adcs",
    specs: {
      size: "0.5 U",
      mass: "2.5 kg",
      power: "5 W",
    },
    tags: ["Precise", "High Torque"],
  }
];
